/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/agent/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List current user's workspaces */
        get: operations["listAgentWorkspaces"];
        put?: never;
        /** Create a workspace */
        post: operations["createAgentWorkspace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent/workspaces/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Workspace identifier. */
                id: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        /** Get a workspace */
        get: operations["getAgentWorkspace"];
        /** Update a workspace */
        put: operations["updateAgentWorkspace"];
        post?: never;
        /** Delete a workspace */
        delete: operations["deleteAgentWorkspace"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent/workspaces/{id}/active": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Workspace identifier. */
                id: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        get?: never;
        /** Mark a workspace active for the current user and tenant */
        put: operations["activateAgentWorkspace"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent/workspaces/{wsId}/rooms": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Workspace identifier for scoped room operations. */
                wsId: components["parameters"]["WorkspaceScopeId"];
            };
            cookie?: never;
        };
        /** List rooms in a workspace */
        get: operations["listAgentRooms"];
        put?: never;
        /** Create a room in a workspace */
        post: operations["createAgentRoom"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent/rooms/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Room identifier. */
                id: components["parameters"]["RoomId"];
            };
            cookie?: never;
        };
        /** Get a room */
        get: operations["getAgentRoom"];
        /** Update a room */
        put: operations["updateAgentRoom"];
        post?: never;
        /** Delete a room */
        delete: operations["deleteAgentRoom"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent/rooms/{id}/config": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Room identifier. */
                id: components["parameters"]["RoomId"];
            };
            cookie?: never;
        };
        /** Get room configuration */
        get: operations["getAgentRoomConfig"];
        /** Update room configuration */
        put: operations["updateAgentRoomConfig"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent/rooms/{id}/bindings": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Room identifier. */
                id: components["parameters"]["RoomId"];
            };
            cookie?: never;
        };
        /** List active room bindings */
        get: operations["listAgentRoomBindings"];
        put?: never;
        /** Create a room binding */
        post: operations["createAgentRoomBinding"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent/bindings/{bindingId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Binding identifier. */
                bindingId: components["parameters"]["BindingId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a room binding */
        delete: operations["deleteAgentRoomBinding"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent/rooms/{id}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Room identifier. */
                id: components["parameters"]["RoomId"];
            };
            cookie?: never;
        };
        /** List task run summaries for a room */
        get: operations["listAgentRoomTasks"];
        put?: never;
        /** Start a task in a room */
        post: operations["startAgentRoomTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent/rooms/{id}/tasks/{taskId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Room identifier. */
                id: components["parameters"]["RoomId"];
                /** @description Task run identifier. */
                taskId: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        /** Get a task run with embedded events */
        get: operations["getAgentRoomTask"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent/rooms/{id}/tasks/{taskId}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Room identifier. */
                id: components["parameters"]["RoomId"];
                /** @description Task run identifier. */
                taskId: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        /**
         * Stream task events
         * @description Each SSE data field contains one TaskEvent JSON payload.
         */
        get: operations["streamAgentRoomTaskEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent/team-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List available team templates
         * @description Lists templates sourced from HiMarket products and Nacos.
         */
        get: operations["listAgentTeamTemplates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent/team-templates/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team template identifier. */
                id: components["parameters"]["TeamTemplateId"];
            };
            cookie?: never;
        };
        /** Get a team template */
        get: operations["getAgentTeamTemplate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        WorkspacePage: {
            content: components["schemas"]["Workspace"][];
            /** Format: int64 */
            totalElements: number;
            /** Format: int32 */
            totalPages: number;
            /** Format: int32 */
            size: number;
            /** Format: int32 */
            number: number;
            first: boolean;
            last: boolean;
        };
        Workspace: {
            id: string;
            name: string;
            description?: string;
            ownerId: string;
            defaultTeamTemplateId?: string;
            isActive: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateWorkspaceRequest: {
            name: string;
            description?: string;
            defaultTeamTemplateId?: string;
        };
        UpdateWorkspaceRequest: {
            name: string;
            description?: string;
            defaultTeamTemplateId?: string;
        };
        RoomList: components["schemas"]["Room"][];
        Room: {
            id: string;
            workspaceId: string;
            name: string;
            modelId: string;
            teamTemplateId: string;
            fileRoot?: string;
            permission: components["schemas"]["RoomPermission"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateRoomRequest: {
            name: string;
            teamTemplateId: string;
            modelId: string;
            description?: string;
        };
        UpdateRoomRequest: {
            name: string;
            teamTemplateId: string;
            modelId: string;
            description?: string;
        };
        RoomConfig: {
            roomId: string;
            modelId: string;
            teamTemplateId: string;
            skillBindings: components["schemas"]["BindingRef"][];
            mcpBindings: components["schemas"]["BindingRef"][];
            permission: components["schemas"]["RoomPermission"];
        };
        RoomPermission: {
            readonly: boolean;
            allowedUserIds: string[];
        };
        BindingRef: {
            productId: string;
            version: string;
            status: components["schemas"]["BindingStatus"];
        };
        BindingList: components["schemas"]["Binding"][];
        Binding: {
            id: string;
            roomId: string;
            kind: components["schemas"]["BindingKind"];
            productId: string;
            version: string;
            status: components["schemas"]["BindingStatus"];
            /** Format: date-time */
            createdAt: string;
        };
        CreateBindingRequest: {
            kind: components["schemas"]["BindingKind"];
            productId: string;
            version: string;
        };
        /** @enum {string} */
        BindingKind: "SKILL" | "MCP" | "MODEL";
        /** @enum {string} */
        BindingStatus: "ACTIVE" | "DISABLED";
        StartTaskRequest: {
            prompt: string;
            files?: string[];
            /** @enum {string} */
            mode: "chat" | "task";
        };
        StartTaskResponse: {
            taskId: string;
            status: components["schemas"]["TaskStatus"];
        };
        TaskRunSummaryList: components["schemas"]["TaskRunSummary"][];
        TaskRunSummary: {
            id: string;
            roomId: string;
            status: components["schemas"]["TaskStatus"];
            prompt: string;
            failureExcerpt?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            completedAt?: string;
        };
        TaskRun: {
            id: string;
            roomId: string;
            status: components["schemas"]["TaskStatus"];
            prompt: string;
            plan?: {
                [key: string]: unknown;
            };
            events: components["schemas"]["TaskEvent"][];
            artifacts: components["schemas"]["Artifact"][];
            failureExcerpt?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            completedAt?: string;
        };
        /** @enum {string} */
        TaskStatus: "PENDING" | "RUNNING" | "SUCCEEDED" | "FAILED";
        TaskEvent: {
            /** Format: int32 */
            seq: number;
            /** @enum {string} */
            kind: "plan" | "worker.assigned" | "tool.call" | "file.diff" | "task.failed" | "task.completed" | "log";
            agentId?: string;
            payload: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            timestamp: string;
        };
        Artifact: {
            id: string;
            taskId: string;
            path: string;
            mimeType: string;
            /** Format: int64 */
            size: number;
            sha256: string;
            /** Format: uri-reference */
            downloadUrl: string;
        };
        TeamTemplateList: components["schemas"]["TeamTemplate"][];
        TeamTemplate: {
            id: string;
            name: string;
            version: string;
            manager: components["schemas"]["AgentProfileRef"];
            workers: components["schemas"]["AgentProfileRef"][];
            defaultSkills: string[];
            defaultMcps: string[];
        };
        AgentProfileRef: {
            id: string;
            role: string;
            model: string;
            systemPromptDigest: string;
        };
        Error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    responses: {
        /** @description Invalid request. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing, invalid, or expired bearer token. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Authenticated principal is not allowed to perform this action. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Requested resource was not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Unexpected server error. */
        ServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Workspace identifier. */
        WorkspaceId: string;
        /** @description Workspace identifier for scoped room operations. */
        WorkspaceScopeId: string;
        /** @description Room identifier. */
        RoomId: string;
        /** @description Binding identifier. */
        BindingId: string;
        /** @description Task run identifier. */
        TaskId: string;
        /** @description Team template identifier. */
        TeamTemplateId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listAgentWorkspaces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workspace page for the current user and tenant. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspacePage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            "5XX": components["responses"]["ServerError"];
        };
    };
    createAgentWorkspace: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorkspaceRequest"];
            };
        };
        responses: {
            /** @description Workspace created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            "5XX": components["responses"]["ServerError"];
        };
    };
    getAgentWorkspace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Workspace identifier. */
                id: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workspace detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            "5XX": components["responses"]["ServerError"];
        };
    };
    updateAgentWorkspace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Workspace identifier. */
                id: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateWorkspaceRequest"];
            };
        };
        responses: {
            /** @description Updated workspace. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            "5XX": components["responses"]["ServerError"];
        };
    };
    deleteAgentWorkspace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Workspace identifier. */
                id: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workspace deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            "5XX": components["responses"]["ServerError"];
        };
    };
    activateAgentWorkspace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Workspace identifier. */
                id: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active workspace. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            "5XX": components["responses"]["ServerError"];
        };
    };
    listAgentRooms: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Workspace identifier for scoped room operations. */
                wsId: components["parameters"]["WorkspaceScopeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rooms in the workspace. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            "5XX": components["responses"]["ServerError"];
        };
    };
    createAgentRoom: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Workspace identifier for scoped room operations. */
                wsId: components["parameters"]["WorkspaceScopeId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRoomRequest"];
            };
        };
        responses: {
            /** @description Room created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Room"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            "5XX": components["responses"]["ServerError"];
        };
    };
    getAgentRoom: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Room identifier. */
                id: components["parameters"]["RoomId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Room detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Room"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            "5XX": components["responses"]["ServerError"];
        };
    };
    updateAgentRoom: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Room identifier. */
                id: components["parameters"]["RoomId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRoomRequest"];
            };
        };
        responses: {
            /** @description Updated room. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Room"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            "5XX": components["responses"]["ServerError"];
        };
    };
    deleteAgentRoom: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Room identifier. */
                id: components["parameters"]["RoomId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Room deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            "5XX": components["responses"]["ServerError"];
        };
    };
    getAgentRoomConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Room identifier. */
                id: components["parameters"]["RoomId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Room configuration. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomConfig"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            "5XX": components["responses"]["ServerError"];
        };
    };
    updateAgentRoomConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Room identifier. */
                id: components["parameters"]["RoomId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoomConfig"];
            };
        };
        responses: {
            /** @description Updated room configuration. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomConfig"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            "5XX": components["responses"]["ServerError"];
        };
    };
    listAgentRoomBindings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Room identifier. */
                id: components["parameters"]["RoomId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active Skill, MCP, and Model bindings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BindingList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            "5XX": components["responses"]["ServerError"];
        };
    };
    createAgentRoomBinding: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Room identifier. */
                id: components["parameters"]["RoomId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBindingRequest"];
            };
        };
        responses: {
            /** @description Binding created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Binding"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            "5XX": components["responses"]["ServerError"];
        };
    };
    deleteAgentRoomBinding: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Binding identifier. */
                bindingId: components["parameters"]["BindingId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Binding deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            "5XX": components["responses"]["ServerError"];
        };
    };
    listAgentRoomTasks: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Room identifier. */
                id: components["parameters"]["RoomId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task run summaries. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRunSummaryList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            "5XX": components["responses"]["ServerError"];
        };
    };
    startAgentRoomTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Room identifier. */
                id: components["parameters"]["RoomId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartTaskRequest"];
            };
        };
        responses: {
            /** @description Task accepted for asynchronous execution. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartTaskResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            "5XX": components["responses"]["ServerError"];
        };
    };
    getAgentRoomTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Room identifier. */
                id: components["parameters"]["RoomId"];
                /** @description Task run identifier. */
                taskId: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task run detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRun"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            "5XX": components["responses"]["ServerError"];
        };
    };
    streamAgentRoomTaskEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Room identifier. */
                id: components["parameters"]["RoomId"];
                /** @description Task run identifier. */
                taskId: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task event stream. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["TaskEvent"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            "5XX": components["responses"]["ServerError"];
        };
    };
    listAgentTeamTemplates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Available team templates. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamTemplateList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            "5XX": components["responses"]["ServerError"];
        };
    };
    getAgentTeamTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team template identifier. */
                id: components["parameters"]["TeamTemplateId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Team template with manager and worker profile references. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamTemplate"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            "5XX": components["responses"]["ServerError"];
        };
    };
}
